export const properties = [
  {
    id: 'chelsea-777',
    programName: '777 Chelsea Street',
    city: 'Boston',
    county: 'Suffolk',
    programType: 'General Housing',
    specialization: 'None',
    gender: 'Co-ed',
    capacity: 12,
    availableBeds: 4,
    createdAt: '2024-01-15T14:00:00Z',
    contact: {
      person: 'Karen',
      phone: '617-555-0101',
      email: 'karen@chelseastreet.org',
    },
    notes: 'On bus line, near downtown.',
  },
  {
    id: 'enterprose',
    programName: 'Enterprose House',
    city: 'Boston',
    county: 'Suffolk',
    programType: 'Long-Term',
    specialization: 'Veterans',
    gender: 'Male',
    capacity: 20,
    availableBeds: 6,
    createdAt: '2024-02-02T10:00:00Z',
    contact: {
      person: 'John',
      phone: '617-555-0102',
      email: 'john@enterprose.org',
    },
    notes: 'Veteran-centric programming with job placement support.',
  },
  {
    id: 'lowell-men',
    programName: 'Lowell House - Men',
    city: 'Lowell',
    county: 'Middlesex',
    programType: 'Short-Term',
    specialization: 'Substance Use Recovery',
    gender: 'Male',
    capacity: 16,
    availableBeds: 2,
    createdAt: '2024-01-28T12:00:00Z',
    contact: {
      person: 'Lesly',
      phone: '978-555-0103',
      email: 'lesly@lowellhouse.org',
    },
    notes: 'Evidence-based recovery curriculum and counseling.',
  },
  {
    id: 'mainspring-men',
    programName: 'Mainspring House',
    city: 'Brockton',
    county: 'Plymouth',
    programType: 'Shelter',
    specialization: 'General',
    gender: 'Male',
    capacity: 30,
    availableBeds: 10,
    createdAt: '2024-02-10T09:00:00Z',
    contact: {
      person: 'Amelia',
      phone: '508-555-0104',
      email: 'amelia@mainspring.org',
    },
    notes: 'Night-to-night shelter with warm handoffs to services.',
  },
  {
    id: 'newton-wellsley',
    programName: 'Newton Wellsley Program',
    city: 'Newton',
    county: 'Middlesex',
    programType: 'Transitional',
    specialization: 'Mental Health Support',
    gender: 'Female',
    capacity: 14,
    availableBeds: 3,
    createdAt: '2024-01-21T17:30:00Z',
    contact: {
      person: 'Sarah',
      phone: '617-555-0105',
      email: 'sarah@newtonwellsley.org',
    },
    notes: 'Clinical team on-site twice weekly.',
  },
  {
    id: 'plymouth-house',
    programName: 'Plymouth House',
    city: 'Plymouth',
    county: 'Plymouth',
    programType: 'Reentry',
    specialization: 'Corrections Reentry',
    gender: 'Male',
    capacity: 22,
    availableBeds: 5,
    createdAt: '2024-02-15T08:20:00Z',
    contact: {
      person: 'Luis',
      phone: '508-555-0106',
      email: 'luis@plymouthhouse.org',
    },
    notes: 'Close coordination with parole and employment teams.',
  },
  {
    id: 'pinestreet-general',
    programName: 'Pine Street Inn - General',
    city: 'Boston',
    county: 'Suffolk',
    programType: 'Shelter',
    specialization: 'General',
    gender: 'Co-ed',
    capacity: 40,
    availableBeds: 12,
    createdAt: '2024-02-05T14:45:00Z',
    contact: {
      person: 'Ashley',
      phone: '617-555-0107',
      email: 'ashley@pinestreet.org',
    },
    notes: 'Large facility with health clinic partnership.',
  },
  {
    id: 'pinestreet-health',
    programName: 'Pine Street Inn - Safe & Healthy',
    city: 'Boston',
    county: 'Suffolk',
    programType: 'Shelter',
    specialization: 'Medical Respite',
    gender: 'Female',
    capacity: 18,
    availableBeds: 1,
    createdAt: '2024-01-30T11:15:00Z',
    contact: {
      person: 'Rachel',
      phone: '617-555-0108',
      email: 'rachel@pinestreet.org',
    },
    notes: 'Priority for women needing short-term medical respite.',
  },
  {
    id: 'st-marys',
    programName: "St. Mary's Home",
    city: 'Boston',
    county: 'Suffolk',
    programType: 'Long-Term',
    specialization: 'Families',
    gender: 'Female',
    capacity: 10,
    availableBeds: 4,
    createdAt: '2024-02-18T16:00:00Z',
    contact: {
      person: 'Colene',
      phone: '617-555-0109',
      email: 'colene@stmaryshome.org',
    },
    notes: 'Apartment-style setting with childcare options.',
  },
  {
    id: 'christinas-house',
    programName: "Christina's House",
    city: 'Springfield',
    county: 'Hampden',
    programType: 'Transitional',
    specialization: 'Families',
    gender: 'Female',
    capacity: 12,
    availableBeds: 2,
    createdAt: '2024-02-12T13:10:00Z',
    contact: {
      person: 'Myya',
      phone: '413-555-0110',
      email: 'myya@christinashouse.org',
    },
    notes: 'Faith-based supportive community for mothers.',
  },
];
